.label ACPTR	= $FFA5             // 65445	Input byte from serial port
.label CHKIN	= $FFC6             // 65478	Open channel for input
.label CHKOUT	= $FFC9             // 65481	Open a channel for output
.label CHRIN	= $FFCF             // 65487	Get a character from the input channel
.label CHROUT	= $FFD2             // 65490	Output a character
.label CIOUT	= $FFA8             // 65448	Transmit a byte over the serial bus
.label CINT	= $FF81             // 65409	Initialize the screen editor and VIC-II Chip
.label CLALL	= $FFE7             // 65511	Close all open files
.label CLOSE	= $FFC3             // 65475	Close a logical file
.label CLRCHN	= $FFCC             // 65484	Clear all I/O channels
.label GETIN	= $FFE4             // 65508	Get a character
.label IOBASE	= $FFF3             // 65523	Define I/O memory page
.label IOINIT	= $FF84             // 65412	Initialize I/O devices
.label LISTEN	= $FFB1             // 65457	Command a device on the serial bus to listen
.label LOAD	= $FFD5             // 65493	Load RAM from device
.label MEMBOT	= $FF9C             // 65436	Set bottom of memory
.label MEMTOP	= $FF99             // 65433	Set the top of RAM
.label OPEN	= $FFC0             // 65472	Open a logical file
.label PLOT	= $FFF0             // 65520	Set or retrieve cursor location
.label RAMTAS	= $FF87             // 65415	Perform RAM test
.label RDTIM	= $FFDE             // 65502	Read system clock
.label READST	= $FFB7             // 65463	Read status word
.label RESTOR	= $FF8A             // 65418	Set the top of RAM
.label SAVE	= $FFD8             // 65496	Save memory to a device
.label SCNKEY	= $FF9F             // 65439	Scan the keyboard
.label SCREEN	= $FFED             // 65517	Return screen format
.label SECOND	= $FF93             // 65427	Send secondary address for LISTEN
.label SETLFS	= $FFBA             // 65466	Set up a logical file
.label SETMSG	= $FF90             // 65424	Set system message output
.label SETNAM	= $FFBD             // 65469	Set up file name
.label SETTIM	= $FFDB             // 65499	Set the system clock
.label SETTMO	= $FFA2             // 65442	Set IEEE bus card timeout flag
.label STOP	= $FFE1             // 65505	Check if STOP key is pressed
.label TALK	= $FFB4             // 65460	Command a device on the serial bus to talk
.label TKSA	= $FF96             // 65430	Send a secondary address to a device commanded to talk
.label UDTIM	= $FFEA             // 65514	Update the system clock
.label UNLSN	= $FFAE             // 65454	Send an UNLISTEN command
.label UNTLK	= $FFAB             // 65451	Send an UNTALK command
.label VECTOR	= $FF8D             // 65421	Manage RAM vectors

.label RESET        = $FFFC             // reset vector (FCE2)